# Generated by Django 4.0.6 on 2022-07-14 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='yorny.jpeg', upload_to=''),
        ),
    ]
