# Generated by Django 4.0.6 on 2022-07-14 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('principal', '0006_alter_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Canchas',
            fields=[
                ('idcancha', models.AutoField(db_column='idCancha', primary_key=True, serialize=False)),
                ('ubicacion', models.CharField(max_length=45)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='Canchas/')),
                ('precio', models.FloatField()),
                ('estado', models.CharField(max_length=45)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canchas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
