# Generated by Django 4.0.6 on 2022-07-14 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0007_canchas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='canchas',
            old_name='imagen',
            new_name='image',
        ),
    ]
