# Generated by Django 4.0.6 on 2022-07-26 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0010_alter_perfil_image_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='image',
            field=models.ImageField(default='yorny.jpeg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='yorny.jpeg', upload_to=''),
        ),
    ]
