# Generated by Django 4.0.6 on 2022-08-02 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0012_canchas_correo_electronico_canchas_telefono'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cancha',
        ),
        migrations.DeleteModel(
            name='Personas',
        ),
        migrations.RemoveField(
            model_name='canchas',
            name='correo_electronico',
        ),
        migrations.RemoveField(
            model_name='canchas',
            name='telefono',
        ),
        migrations.AlterField(
            model_name='canchas',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='image',
            field=models.ImageField(default='anonimo.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='anonimo.jpg', upload_to=''),
        ),
    ]
